# Generated by Django 5.0.3 on 2024-04-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("fecha_limite", models.DateTimeField(verbose_name="fecha limite")),
                ("estado", models.CharField(max_length=200)),
            ],
        ),
    ]
