# Generated by Django 5.0.3 on 2024-04-23 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="description",
            new_name="descripcion",
        ),
    ]
